Issue 1076: Stopgap measure to semi-fix the component run scripts

diff --git a/src/main/resources/run-gltrig b/src/main/resources/run-gltrig
--- a/src/main/resources/run-gltrig
+++ b/src/main/resources/run-gltrig
@@ -28,18 +28,35 @@ icebucket \
 concurrent \
 ws-commons-util"
 
+missing_jar=
 CLASSPATH=""
 for proj in ${REQ_PROJECTS}; do
-  CLASSPATH=${WS_DIR}/${proj}/target/${proj}-${pom.version}.jar:${CLASSPATH}
+  jar=${WS_DIR}/${proj}/target/${proj}-${pom.version}.jar
+  if [ -f "$jar" ]; then
+    CLASSPATH=${jar}:${CLASSPATH}
+  else
+    echo "$0: Cannot find ${proj} jar file" >&2
+    missing_jar=true
+  fi
 done
 
 for lib in ${REQ_LIBS}; do
-  # This will break if there is more than one such lib under the REPO_DIR
-  CLASSPATH=`find ${REPO_DIR} -name ${lib}\*.jar`:${CLASSPATH}
+  jar=
+  for i in `find ${REPO_DIR} -name ${lib}\*.jar`; do
+    jar="$i"
+  done
+  if [ -f "$jar" ]; then
+    CLASSPATH=$jar:${CLASSPATH}
+  else
+    echo "$0: Cannot find ${lib} jar file" >&2
+    missing_jar=true
+  fi
 done
+
+if [ ! -z ${missing_jar} ]; then
+  exit 1
+fi
 
 export CLASSPATH
 #echo "CLASSPATH=${CLASSPATH}"
 java icecube.daq.trigger.component.GlobalTriggerComponent $@
-
-#CLASSPATH=$TOPDIR/lib/juggler.jar:$TOPDIR/lib/juggler-test.jar:$TOPDIR/tools/lib/commons-logging.jar:$TOPDIR/tools/lib/junit.jar:$TOPDIR/tools/lib/log4j.jar:$TOPDIR/tools/lib/xmlrpc-common.jar:$TOPDIR/tools/lib/xmlrpc-client.jar:$TOPDIR/tools/lib/ws-commons-util.jar:$TOPDIR/tools/lib/concurrent.jar:$TOPDIR/lib/eventBuilder-prod.jar:$TOPDIR/lib/new-dispatch.jar:$TOPDIR/lib/daq-common.jar:$TOPDIR/lib/icebucket.jar:$TOPDIR/lib/splicer.jar:$TOPDIR/lib/daq-request-filler.jar:$TOPDIR/lib/trigger.jar
diff --git a/src/main/resources/run-iitrig b/src/main/resources/run-iitrig
--- a/src/main/resources/run-iitrig
+++ b/src/main/resources/run-iitrig
@@ -28,15 +28,34 @@ icebucket \
 concurrent \
 ws-commons-util"
 
+missing_jar=
 CLASSPATH=""
 for proj in ${REQ_PROJECTS}; do
-  CLASSPATH=${WS_DIR}/${proj}/target/${proj}-${pom.version}.jar:${CLASSPATH}
+  jar=${WS_DIR}/${proj}/target/${proj}-${pom.version}.jar
+  if [ -f "$jar" ]; then
+    CLASSPATH=${jar}:${CLASSPATH}
+  else
+    echo "$0: Cannot find ${proj} jar file" >&2
+    missing_jar=true
+  fi
 done
 
 for lib in ${REQ_LIBS}; do
-  # This will break if there is more than one such lib under the REPO_DIR
-  CLASSPATH=`find ${REPO_DIR} -name ${lib}\*.jar`:${CLASSPATH}
+  jar=
+  for i in `find ${REPO_DIR} -name ${lib}\*.jar`; do
+    jar="$i"
+  done
+  if [ -f "$jar" ]; then
+    CLASSPATH=$jar:${CLASSPATH}
+  else
+    echo "$0: Cannot find ${lib} jar file" >&2
+    missing_jar=true
+  fi
 done
+
+if [ ! -z ${missing_jar} ]; then
+  exit 1
+fi
 
 export CLASSPATH
 #echo "CLASSPATH=${CLASSPATH}"
